//! Manual/Nostr signaling payload types and encoding/decoding.
//!
//! Supports signaling format:
//! - v1 (Custom/Nostr mode): ICE/QUIC with str0m + quinn

use anyhow::{anyhow, Context, Result};
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use crc32fast::Hasher;
use serde::{Deserialize, Serialize};

/// Version 1: Custom mode (str0m ICE + quinn QUIC)
pub const MANUAL_SIGNAL_VERSION: u16 = 1;

pub(crate) const PREFIX: &str = "TRS";
pub const LINE_WIDTH: usize = 76;

// ============================================================================
// Custom Mode (v1) - str0m ICE + quinn QUIC
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManualOffer {
    pub version: u16,
    pub ice_ufrag: String,
    pub ice_pwd: String,
    pub candidates: Vec<String>,
    pub quic_fingerprint: String,
    /// Session ID to distinguish between different signaling sessions (for nostr mode)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Requested source endpoint (e.g., "tcp://127.0.0.1:22")
    /// Required for receiver-initiated handshake in manual modes
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManualAnswer {
    pub version: u16,
    pub ice_ufrag: String,
    pub ice_pwd: String,
    pub candidates: Vec<String>,
    /// Session ID echoed from offer (for nostr mode)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// QUIC server fingerprint for custom-manual mode (sender is QUIC server)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quic_fingerprint: Option<String>,
}

/// Request from receiver to initiate a tunnel session (for nostr mode).
/// Contains receiver's ICE credentials, sent before offer to trigger session start.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManualRequest {
    pub version: u16,
    pub ice_ufrag: String,
    pub ice_pwd: String,
    pub candidates: Vec<String>,
    /// Session ID generated by receiver to filter stale events
    pub session_id: String,
    /// Unix timestamp (seconds) when request was created
    pub timestamp: u64,
    /// Requested source endpoint (e.g., "tcp://127.0.0.1:22")
    /// If None, sender uses its default source
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

/// Maximum length for rejection reason to prevent excessively large messages.
pub const MAX_REJECT_REASON_LENGTH: usize = 512;

/// Truncate a rejection reason to the maximum allowed length.
/// If truncation is needed, appends "..." suffix at a valid UTF-8 boundary.
pub(crate) fn truncate_reason(reason: String, max_len: usize) -> String {
    const TRUNCATION_SUFFIX: &str = "...";
    if reason.len() > max_len {
        let max_content_len = max_len.saturating_sub(TRUNCATION_SUFFIX.len());
        let truncated = &reason[..reason.floor_char_boundary(max_content_len)];
        format!("{}{}", truncated, TRUNCATION_SUFFIX)
    } else {
        reason
    }
}

/// Rejection response from sender when it cannot accept a session (for nostr mode).
/// Sent when sender is at capacity or otherwise unable to handle the request.
/// The session_id is echoed from the original request so the receiver can match it.
///
/// # Note on encode/decode helpers
///
/// Unlike [`ManualOffer`] and [`ManualAnswer`], this struct intentionally lacks
/// `encode_reject`/`decode_reject`/`display_reject` helpers. Those helpers are
/// designed for the manual stdin/stdout signaling mode with PEM-like markers.
/// `ManualReject` is only used in Nostr mode, where it is serialized directly
/// as JSON via `serde_json` before base64 encoding for transmission.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManualReject {
    pub version: u16,
    /// Session ID echoed from request
    pub session_id: String,
    /// Rejection reason (truncated to [`MAX_REJECT_REASON_LENGTH`] bytes)
    pub reason: String,
}

impl ManualReject {
    /// Create a new rejection with the given session ID and reason.
    /// The reason will be truncated if it exceeds [`MAX_REJECT_REASON_LENGTH`].
    pub fn new(session_id: String, reason: String) -> Self {
        Self {
            version: MANUAL_SIGNAL_VERSION,
            session_id,
            reason: truncate_reason(reason, MAX_REJECT_REASON_LENGTH),
        }
    }
}

// ============================================================================
// Encoding/Decoding
// ============================================================================

pub fn encode_offer(offer: &ManualOffer) -> Result<String> {
    encode_payload(offer)
}

pub fn decode_offer(payload: &str) -> Result<ManualOffer> {
    decode_payload(payload)
}

pub fn encode_answer(answer: &ManualAnswer) -> Result<String> {
    encode_payload(answer)
}

pub fn decode_answer(payload: &str) -> Result<ManualAnswer> {
    decode_payload(payload)
}

// ============================================================================
// Internal Helpers
// ============================================================================

fn encode_payload<T: Serialize>(payload: &T) -> Result<String> {
    encode_payload_v(payload, MANUAL_SIGNAL_VERSION)
}

fn encode_payload_v<T: Serialize>(payload: &T, version: u16) -> Result<String> {
    let json = serde_json::to_vec(payload).context("Failed to serialize manual payload")?;
    let checksum = crc32(&json);
    let encoded = URL_SAFE_NO_PAD.encode(&json);
    Ok(format!(
        "{}{}:{:08x}:{}",
        PREFIX, version, checksum, encoded
    ))
}

fn decode_payload<T: for<'de> Deserialize<'de>>(payload: &str) -> Result<T> {
    decode_payload_v(payload, MANUAL_SIGNAL_VERSION)
}

fn decode_payload_v<T: for<'de> Deserialize<'de>>(
    payload: &str,
    expected_version: u16,
) -> Result<T> {
    let trimmed = payload.trim();
    let mut parts = trimmed.splitn(3, ':');
    let header = parts
        .next()
        .ok_or_else(|| anyhow!("Invalid manual payload header"))?;
    let checksum_hex = parts
        .next()
        .ok_or_else(|| anyhow!("Invalid manual payload checksum"))?;
    let body = parts
        .next()
        .ok_or_else(|| anyhow!("Invalid manual payload body"))?;

    if !header.starts_with(PREFIX) {
        return Err(anyhow!("Manual payload missing prefix"));
    }

    let version_str = header
        .strip_prefix(PREFIX)
        .ok_or_else(|| anyhow!("Manual payload missing version"))?;
    let version: u16 = version_str
        .parse()
        .map_err(|_| anyhow!("Invalid signaling version: {:?}", version_str))?;
    if version != expected_version {
        return Err(anyhow!(
            "Signaling version mismatch (expected {}, got {})",
            expected_version,
            version
        ));
    }

    let expected_crc =
        u32::from_str_radix(checksum_hex, 16).context("Invalid manual payload checksum")?;
    let decoded = URL_SAFE_NO_PAD
        .decode(body.as_bytes())
        .context("Manual payload base64 decode failed")?;

    let actual_crc = crc32(&decoded);
    if actual_crc != expected_crc {
        return Err(anyhow!(
            "Manual payload checksum mismatch (expected {:08x}, got {:08x})",
            expected_crc,
            actual_crc
        ));
    }

    let parsed: T = serde_json::from_slice(&decoded).context("Manual payload JSON parse failed")?;
    Ok(parsed)
}

fn crc32(bytes: &[u8]) -> u32 {
    let mut hasher = Hasher::new();
    hasher.update(bytes);
    hasher.finalize()
}

/// Wrap a string into lines of at most `width` characters.
///
/// # Precondition
/// The input string `s` must contain only ASCII characters (as is the case for
/// base64-encoded payloads with ASCII prefix/checksum). This function chunks by
/// bytes for efficiency, which is safe for ASCII but would split multi-byte UTF-8
/// codepoints. The function will panic if given non-ASCII input.
pub(crate) fn wrap_lines(s: &str, width: usize) -> String {
    assert!(
        s.is_ascii(),
        "wrap_lines requires ASCII input; got non-ASCII characters"
    );
    s.as_bytes()
        .chunks(width)
        .map(|chunk| {
            std::str::from_utf8(chunk)
                .expect("wrap_lines: chunk is not valid UTF-8; input must be ASCII")
        })
        .collect::<Vec<_>>()
        .join("\n")
}
